
debug: True
deterministic: False
automatic_optimization: True
wandb_offline: True
debug_num_workers: 10
debug_max_epochs: 10

cnn_type: 'resnet18'
landsat8_bands: 'ALL'
landsat8_normalize: True
use_h5: True

do_test: False
do_train: True
num_sanity_val_steps: 0

train:
  accelerator: 'gpu'

tile2vec:
  margin: 1.0

pretrain:
  batch_size: 25
  val_batch_size: 25
  loss_type: 'sssl'
  augmentations: 'sssl'   # 'rel_reasoning'
  space_pair_limit: 0.15
  space_limit_type: 'admin'
  time_pair_limit: 1
  K: 8
  lr: 0.0001
  weight_decay: 0.01
