do_pretrain: False
pretrained_on: 'ImageNet'   # random, ImageNet, own
downstream_cfg:
  - 'config/ipc/ImageNet_frz_mlp_100.yaml'
  - 'config/ipc/ImageNet_frz_mlp_100_bin.yaml'
  - 'config/ipc/ImageNet_frz_mlp_70.yaml'
  - 'config/ipc/ImageNet_frz_mlp_50.yaml'
  - 'config/ipc/ImageNet_frz_mlp_20.yaml'
  - 'config/ipc/ImageNet_frz_mlp_5.yaml'
  - 'config/ipc/ImageNet_frz_mlp_1.yaml'
  - 'config/ipc/ImageNet_ft_mlp_100.yaml'
  - 'config/ipc/ImageNet_ft_mlp_100_bin.yaml'
  - 'config/ipc/ImageNet_ft_mlp_70.yaml'
  - 'config/ipc/ImageNet_ft_mlp_50.yaml'
  - 'config/ipc/ImageNet_ft_mlp_20.yaml'
  - 'config/ipc/ImageNet_ft_mlp_5.yaml'
  - 'config/ipc/ImageNet_ft_mlp_1.yaml'
  - 'config/ipc/ImageNet_ft_mlp_100_0fut_after202003_bin.yaml'
  - 'config/ipc/ImageNet_ft_mlp_100_1fut_after202003_bin.yaml'
  - 'config/ipc/ImageNet_ft_mlp_100_2fut_after202003_bin.yaml'
  - 'config/ipc/ImageNet_ft_mlp_100_3fut_after202003_bin.yaml'
  - 'config/ipc/ImageNet_frz_mlp_100_0fut_after202003_bin.yaml'
  - 'config/ipc/ImageNet_frz_mlp_100_1fut_after202003_bin.yaml'
  - 'config/ipc/ImageNet_frz_mlp_100_2fut_after202003_bin.yaml'
  - 'config/ipc/ImageNet_frz_mlp_100_3fut_after202003_bin.yaml'
