do_pretrain: False
pretrained_on: 'random'   # random, ImageNet, own
downstream_cfg:
  - 'config/ipc/random_frz_mlp_100_RGB.yaml'
  - 'config/ipc/random_frz_mlp_100_RGB_bin.yaml'
  - 'config/ipc/random_frz_mlp_70_RGB.yaml'
  - 'config/ipc/random_frz_mlp_50_RGB.yaml'
  - 'config/ipc/random_frz_mlp_20_RGB.yaml'
  - 'config/ipc/random_frz_mlp_5_RGB.yaml'
  - 'config/ipc/random_frz_mlp_1_RGB.yaml'
  - 'config/ipc/random_ft_mlp_100_RGB.yaml'
  - 'config/ipc/random_ft_mlp_100_RGB_bin.yaml'
  - 'config/ipc/random_ft_mlp_70_RGB.yaml'
  - 'config/ipc/random_ft_mlp_50_RGB.yaml'
  - 'config/ipc/random_ft_mlp_20_RGB.yaml'
  - 'config/ipc/random_ft_mlp_5_RGB.yaml'
  - 'config/ipc/random_ft_mlp_1_RGB.yaml'
  - 'config/ipc/random_ft_mlp_100_RGB_0fut_after202003_bin.yaml'
  - 'config/ipc/random_ft_mlp_100_RGB_1fut_after202003_bin.yaml'
  - 'config/ipc/random_ft_mlp_100_RGB_2fut_after202003_bin.yaml'
  - 'config/ipc/random_ft_mlp_100_RGB_3fut_after202003_bin.yaml'
  - 'config/ipc/random_frz_mlp_100_RGB_0fut_after202003_bin.yaml'
  - 'config/ipc/random_frz_mlp_100_RGB_1fut_after202003_bin.yaml'
  - 'config/ipc/random_frz_mlp_100_RGB_2fut_after202003_bin.yaml'
  - 'config/ipc/random_frz_mlp_100_RGB_3fut_after202003_bin.yaml'
